site_name: SRT-CTF.ZIP
site_url: https://srt-ctf.zip

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest
  custom_dir: overrides

plugins:
  - search
  - roamlinks
  - obsidian-support
  - mkdocs-pdf
  - blog:
      blog_dir: blog
  - redirects:
      redirect_maps:
      'posts/2023/12/the-return-of-the-yeti.md': "blog/2023/12/11/the-return-of-the-yeti/"
  - rss:
      match_path: blog/blog/.*
      date_from_meta:
        as_creation: date
      categories:
      - categories
      - tags

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true


extra:
  analytics:
    provider: custom

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
